services:
  database:
    image: postgres

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/ecommerce.sql:/docker-entrypoint-initdb.d/ecommerce.sql

    ports:
      - "5434:5432"


  backend:
    build: ./backend

    ports:
      - "8000:8000"

    environment:
      DB_HOST : database
      DB_PORT : 5432
      DB_USER : ${DB_USER}
      DB_PASS : ${DB_PASS}
      DB_NAME : ${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}

    depends_on:
      - database

  
  frontend:
    build: ./frontend

    ports:
      - "5173:5173"
    
    depends_on:
      - backend


volumes:
  postgres_data:



